### ISSUE TITLE
WebUSB support (e.g. Trezor model T)

### ISSUE THREAD

**Issue by Sjors** [achow101/HWI#55]
The Trezor model T uses [webusb](https://wicg.github.io/webusb/) to communicate (see https://github.com/achow101/HWI/issues/38#issuecomment-427032492). I believe Ledger Nano S [supports U2F](https://github.com/LedgerHQ/ledger-wallet-chrome/issues/88#issuecomment-363222976).

I'm not entirely clear on the differences between webusb and U2F.

I'm guessing trying and studying https://github.com/trezor/python-trezor would be a good place to start.

**Comment by Sjors** [comment]
This shouldn't be too hard. E.g. if I use `python-trezor` I can reproduce the same address as their web wallet shows:

```
trezorctl get_address --coin Testnet --script-type p2shsegwit --address "m/49'/1'/0'/0/0"
```

Bech32 works too: `--script-type=segwit` (legacy is `--script-type=address`)

I'm able to get an account xpub:

```
trezorctl get_public_node --coin Testnet -n "m/49'/1'/0'"
```

We can also get the master public key, from which we can derive the master fingerprint:
```
trezorctl get_public_node --coin Testnet -n ""
```

Account xpubs and the master xpub (fingerprint) should be all we need for the `importmulti` support.

**Comment by matejcik** [comment]
WebUSB and HID are two ways to work with USB devices; U2F is a security token protocol over HID which is not important here.

python-trezor can enumerate and work with webusb devices just fine. The problem here is that HWI does its own enumeration using HID (instead of the custom enumeration from python-trezor) and then tries to open TrezorClient with a HID path which is not valid. I have a patch in the works for this, but I'm not sure when I get to finish it.

**Comment by Sjors** [comment]
@matejcik the easiest might be to call `python-trezor` enumerate as well and just append it to the list?

**Comment by matejcik** [comment]
there's some further modifications needed to pass correct paths and/or finished client instances, but yes, that's essentially it.

**Comment by Sjors** [comment]
Trezor T will work once #66 is merged.
